### ISSUE TITLE
Not working with Spring Boot 3

### ISSUE THREAD

**Issue by eliasbalasis** [snowdrop/narayana-spring-boot#156]
We rely heavily on the SpringBoot dependencies chain and we unfortunately have to upgrade to SpringBoot 3

`Could not find class [org.springframework.boot.autoconfigure.transaction.jta.JtaProperties]`

This is part of `spring-boot-autoconfigure-2.6.13` but not part of `spring-boot-autoconfigure-3.2.7`

Is it possible to create a version that works with Spring Boot 3 ?

**Comment by graben** [comment]
All versions since 3.0.0 are working with Spring Boot 3. Try latest 3.1.1 but be aware that many things have changed in Spring Boot itself. Please follow their migration [guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide). Also, have a look at our examples and the README.md.

**Comment by eliasbalasis** [comment]
Thanks @graben.
However, I was unable to find the Maven coordinates, hence my assumption that the framework had not moved forward.

`me.snowdrop:narayana-spring-boot-starter:3.x`
Where can I find this? In which repo?

**Comment by graben** [comment]
Actual starter is available under `dev.snowdrop:narayana-spring-boot-starter:3.1.1` in [maven central](https://central.sonatype.com/artifact/dev.snowdrop/narayana-spring-boot-starter).

**Comment by eliasbalasis** [comment]
Thanks, I found it.

The prefix had changed, from `me.snowdrop` to `dev.snowdrop`
