### ISSUE TITLE
Honoring spring.jta.narayana.default-timeout

### ISSUE THREAD

**Issue by albfan** [snowdrop/narayana-spring-boot#74]
Hi, looks like snowdrop redefines timeout property `spring.jta.narayana.default-timeout` with `narayana.defaultTimeout`

Is it possible to honor that property if it is present?

**Comment by gytis** [comment]
@albfan starting with the Spring Boot 2.1.0 release the Narayana starter has been moved here from the `spring-projects/spring-boot` repository. Since then the property `spring.jta.narayana.default-timeout` does not exist. Which version are you using?

**Comment by fmarchioni** [comment]
Thanks @gytis . Well this requests originated from a customer case where SpringBoot uses narayana to manage transactions. I'll request this info to the customer.

**Comment by fmarchioni** [comment]
@albfan I think we had better to document this shift in the PAM-SpringBoot documentation so that it's clear to the customers

**Comment by albfan** [comment]
Hi @gytis I see the property in version 1.4.3: https://docs.spring.io/spring-boot/docs/1.4.3.RELEASE/reference/html/common-application-properties.html

> spring.jta.narayana.default-timeout=60 # Transaction timeout in seconds.

But not in 2.1.0:

https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/common-application-properties.html

(there's no mention to narayana or snowdrop)

@fmarchioni Not sure if this needs to be documented outside springboot

**Comment by gytis** [comment]
Let me try to explain it more clearly.

We've implemented a Narayana Spring Boot integration and placed it in a Spring Boot repository starting with the Spring Boot 1.4.0. We've implemented it and kind of gave it away to Spring Boot to maintain it.
However, later on, around the 2.0.x timeframe, we started to face some issues with pushing the changes there. Also, they've hinted on planning to remove the Narayan integration in the future anyway. So we've decided to take out the integration and place it in a Snowdrop organization. As a result, for some time there were two Narayana Spring Boot integrations: one in Spring Boot org and one in Snowdrop org. Both had the same features but because of different namespaces they had different property prefixes.
Eventually starting with the Spring Boot 2.1.0 the integration that was in the Spring Boot org was removed and only the Snowdrop one remained. That is why you don't see any Narayana or Snowdrop mentioned in the Spring Boot documentation after 2.1.0.

The problem that you're having is that you use a Snowdrop version of a Narayana integration and try to configure it with a Spring Boot integration property.

**Comment by albfan** [comment]
Thanks @gytis, that makes sense.

Is there any release note where this change is documented? Looking at mvn:dependency looks like project still use narayana and snowdrop is just integration

```
[INFO] +- org.kie:kie-server-spring-boot-starter:jar:7.52.0.Final:compile
[INFO] |  +- me.snowdrop:narayana-spring-boot-starter:jar:2.3.0:compile
[INFO] |  |  \- me.snowdrop:narayana-spring-boot-core:jar:2.3.0:compile
[INFO] |  |     +- org.jboss.narayana.jta:jta:jar:5.9.8.Final:compile
[INFO] |  |     |  +- org.jboss.narayana:common:jar:5.9.8.Final:compile
[INFO] |  |     |  \- org.jboss.narayana.arjunacore:arjuna:jar:5.9.8.Final:compile
[INFO] |  |     |     \- sun.jdk:jconsole:jar:jdk:system
```

**Comment by gytis** [comment]
> Is there any release note where this change is documented?

We don't have much more Spring Boot related docs that what's in the README to be fair. 


> Looking at mvn:dependency looks like project still use narayana and snowdrop is just integration

Yes, that's what most of the Spring Boot starters do. They wrap an existing project and bootstrap it in a Spring Boot environment.

**Comment by geoand** [comment]
Closing as out of date
